// 未经实测的演练参数集中在此。场地坐标均为示意。
export const CONFIG = {
  idleSpeed: 2,
  bossHp: null, // null 按团队输出预算估算；数字可手动覆盖
  bossTargetDuration: 284,
  playerDamageBudget: 0.8,
  syncBossAtMechanics: true,
  calibrateFinalDps: true,
  finalDpsTargetDuration: 5.5,
  aiDps: 70,
  healerDps: 20,
  attackDamage: 140,
  attackInterval: 0.35,
  attackRange: 190,
  speed: 160,
  aoeDamage: 80,
  knifeDamage: 35,
  knifeGoldRadiusMeters: 6,
  arenaUnitsPerMeter: 15, // 示意场地比例，可按实机校准
  pushTapGrace: 0.7,
  pushMissDamage: 25,
  healPerSecond: 3,
  selfRevives: Infinity,
  selfDelay: 5,
  rescueTime: 5,
  rescueHp: 30,
  rescues: 5,
  swordHp: 3780, // 3150 再提高 20%；默认演练故意留一把小剑，不要求 AI 全清
  aiSwordDamageMultiplier: 1.6,
  fullAiSideSwordDamageMultiplier: 1.5, // 保留既定补偿，不随加血提高到 1.8 抵消留剑设计
  cleaveImpactAt: 5,
  cleaveEndBossRatio: 0.05,
  soulHp: 9600,
  soulResolveAt: 18,
  soulBossOffset: 105,
  swordLifetime: 10,
  allowedSwordMisses: 2,
  qiMarkInterval: 1.2,
  qiFirstKnifeAt: 7.5,
  qiKnifeInterval: 0.85,
  qiResolveAt: 15,
  rageImpactAt: 4,
  rageParryEarly: 0.25,
  rageParryLate: 0.2,
};
export const DEFAULT_TEAM = 1;
