// Video timestamps minus 3 seconds. Telegraph intervals are training approximations.
// bossHpRatio values are editable rehearsal anchors, not measured video health.
export const TIMELINE = [
  {
    id: "orbs-01",
    bossHpRatio: 1,
    type: "orbs",
    name: "入幻结算",
    at: 0,
    duration: 11,
  },
  {
    id: "rings-01",
    bossHpRatio: 0.96,
    type: "rings",
    name: "幻魇涌动",
    at: 27,
    duration: 6,
  },
  {
    id: "fire-01",
    bossHpRatio: 0.9,
    type: "fire",
    name: "幽火引烛",
    at: 47,
    duration: 8,
  },
  {
    id: "soul-01",
    bossHpRatio: 0.85,
    type: "soul",
    name: "摄魂之见",
    at: 63,
    duration: 12,
  },
  {
    id: "mist-01",
    bossHpRatio: 0.78,
    type: "mist",
    name: "幻雾一现",
    at: 87,
    duration: 9,
  },
  {
    id: "illusion-01",
    bossHpRatio: 0.74,
    type: "illusion",
    name: "幻象迷踪",
    at: 99,
    duration: 19,
  },
  {
    id: "fire-02",
    bossHpRatio: 0.65,
    type: "fire",
    name: "幽火引烛",
    at: 131,
    duration: 8,
  },
  {
    id: "aoe-01",
    bossHpRatio: 0.58,
    type: "aoe",
    name: "引破幻障",
    at: 156,
    duration: 5,
  },
  {
    id: "shield-01",
    bossHpRatio: 0.55,
    type: "shield",
    name: "超脱凡躯·蜕",
    at: 165,
    duration: 18,
  },
  {
    id: "green-01",
    bossHpRatio: 0.5,
    type: "green",
    name: "幻魇倾泻·启",
    at: 189,
    duration: 7,
  },
  {
    id: "cleave-01",
    bossHpRatio: 0.46,
    type: "cleave",
    name: "怒蟒斩业",
    at: 207,
    duration: 3,
  },
  {
    id: "gaze-01",
    bossHpRatio: 0.43,
    type: "gaze",
    name: "冰冷注视",
    at: 218,
    duration: 5,
  },
  {
    id: "mark-01",
    bossHpRatio: 0.38,
    type: "mark",
    name: "污染刻印",
    at: 238,
    duration: 4,
  },
  {
    id: "spray-01",
    bossHpRatio: 0.35,
    type: "spray",
    name: "毒素喷流",
    at: 250,
    duration: 17,
  },
  {
    id: "sweep-01",
    bossHpRatio: 0.29,
    type: "sweep",
    name: "盘蛇横绝",
    at: 275,
    duration: 4,
  },
  // One composite event: heart deadline and shield cast end are the same instant.
  {
    id: "heart-01",
    bossHpRatio: 0.27,
    shieldBossHpRatio: 0.2,
    type: "heart",
    name: "种下心魔 / 超脱凡躯",
    at: 281,
    duration: 36,
  },
  {
    id: "poison-fans-01",
    bossHpRatio: 0.15,
    type: "poisonFans",
    name: "执迷幻象",
    at: 332,
    duration: 8,
  },
  {
    id: "final-01",
    bossHpRatio: 0.08,
    type: "final",
    name: "幻魇迷乱",
    at: 363,
    duration: 26,
  },
];
export const P1_END = 184;
